name: CI-Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.4
    - name: Build Docker Images
      run: |
        make config
        make build
        make push
